permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
title : blog.ashleytowns.id.au
tagline: rant rant rant
author :
  name : Ashley Towns
  email : ashleyis@me.com